// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules/module-1-ros2',
        },
      ],
    },
    // Additional modules will be added here as they are created
  ],
};

module.exports = sidebars;